### PR TITLE
Changed roboticsConsole to HoM/CE access from RD

### PR DESCRIPTION
**Pull request by Lyroth001**
## About the PR

Robotics console now needs CE/HoM access

## Why / Balance

RD was ~~taken out back and shot~~ retired to a farm upstate until sci rework, and borgs are now under maintenance, so makes sense to switch it to HoM (Not entirely sure why we havent just kept engi but thats fine) 

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

### CODE REVIEW

**Comment by Lyroth001** [comment]
changes work in game, i assume test fail is unreleated (also was on a pr i got merged upstream so probably fine)

**Comment by Lyroth001** [comment]
I love it when things just decide to work now. It is my favourite thing

**Comment by Truoizys** [comment]
oh yeah that was me messing with the workflow, and yeah its some upstream issue with nukies

**Comment by Truoizys** [comment]
as usual

**Comment by Truoizys** [comment]
will probably close this till the new access labels get added, feel free to reopen it or whatever when they exist

**Pull request closed without merging**
